version: "3.9"
services:
  flask_app:
    container_name: flask_app
    volumes:
      # below line for development purposes only. Enabling developer to see changes instantely without the need to rebuild
      - .:/var/task
    build: .
    ports:
      - "8080:8080"
    env_file:
      - ./devops/envs/local.env
    restart: always
    entrypoint: python3 -m flask run --host=0.0.0.0 --port=8080
    depends_on:
      - dynamodb
    links:
      - dynamodb
  dynamodb:
    container_name: dynamodb
    image: amazon/dynamodb-local:latest
    command: "-jar DynamoDBLocal.jar -sharedDb -dbPath ./data"
    volumes:
      - "/docker/dynamodb:/home/dynamodblocal/data"
    working_dir: /home/dynamodblocal
    ports:
      - "8000:8000"

networks:
  default:
    name: app_custom_network

volumes:
  docker:
